dist: trusty
sudo: required

language: python

services:
  - docker

before_install:
  - echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
  - sudo apt-get -qq update
  - echo java --version
  - sudo apt-get install sbt

install:
  - pip install "molecule==1.25.0"
  - pip install -U "ansible==2.3.2.0"
  - pip install docker

script:
  - molecule test --driver docker

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/